// Licensed under the Hungry Ghost Hive License. See LICENSE.

import * as logger from '../../utils/logger.js';
import type { JiraClient } from './client.js';
import type { AdfDocument } from './types.js';

/**
 * Data required to generate a feature sign-off report.
 */
export interface SignOffReportData {
  requirementId: string;
  requirementTitle: string;
  featureBranch: string;
  passed: boolean;
  totalTests: number;
  passedTests: number;
  failedTests: number;
  duration?: string;
  failedTestNames?: string[];
  errorSummary?: string;
  storiesMerged: number;
  teamNames: string[];
}

/**
 * Build an ADF document for a feature sign-off report.
 *
 * @param data - The report data
 * @returns An ADF document suitable for posting as a Jira comment
 */
export function buildSignOffReportAdf(data: SignOffReportData): AdfDocument {
  const content: any[] = [];

  // Header with pass/fail status
  const statusEmoji = data.passed ? ':white_check_mark:' : ':x:';
  const statusText = data.passed ? 'PASSED' : 'FAILED';

  content.push({
    type: 'heading',
    attrs: { level: 3 },
    content: [
      { type: 'emoji', attrs: { shortName: statusEmoji } },
      {
        type: 'text',
        text: ` Feature Sign-Off: ${statusText}`,
        marks: [{ type: 'strong' }],
      },
    ],
  });

  // Requirement info
  content.push({
    type: 'paragraph',
    content: [
      { type: 'text', text: 'Requirement: ', marks: [{ type: 'strong' }] },
      { type: 'text', text: `${data.requirementId} — ${data.requirementTitle}` },
    ],
  });

  content.push({
    type: 'paragraph',
    content: [
      { type: 'text', text: 'Feature Branch: ', marks: [{ type: 'strong' }] },
      { type: 'text', text: data.featureBranch, marks: [{ type: 'code' }] },
    ],
  });

  // Test results table
  const testRows: any[] = [
    // Header row
    {
      type: 'tableRow',
      content: [
        {
          type: 'tableHeader',
          content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Metric' }] }],
        },
        {
          type: 'tableHeader',
          content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Value' }] }],
        },
      ],
    },
    // Total tests
    buildTableRow('Total Tests', String(data.totalTests)),
    // Passed
    buildTableRow('Passed', String(data.passedTests)),
    // Failed
    buildTableRow('Failed', String(data.failedTests)),
  ];

  if (data.duration) {
    testRows.push(buildTableRow('Duration', data.duration));
  }

  testRows.push(buildTableRow('Stories Merged', String(data.storiesMerged)));
  testRows.push(buildTableRow('Teams', data.teamNames.join(', ') || 'N/A'));

  content.push({
    type: 'table',
    attrs: { isNumberColumnEnabled: false, layout: 'default' },
    content: testRows,
  });

  // Failed test details (only if there are failures)
  if (!data.passed && data.failedTestNames && data.failedTestNames.length > 0) {
    content.push({
      type: 'heading',
      attrs: { level: 4 },
      content: [{ type: 'text', text: 'Failed Tests' }],
    });

    content.push({
      type: 'orderedList',
      attrs: { order: 1 },
      content: data.failedTestNames.map(name => ({
        type: 'listItem',
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: name, marks: [{ type: 'code' }] }],
          },
        ],
      })),
    });
  }

  // Error summary (only if present)
  if (!data.passed && data.errorSummary) {
    content.push({
      type: 'heading',
      attrs: { level: 4 },
      content: [{ type: 'text', text: 'Error Summary' }],
    });

    content.push({
      type: 'codeBlock',
      attrs: { language: 'text' },
      content: [{ type: 'text', text: data.errorSummary }],
    });
  }

  // Footer
  content.push({
    type: 'paragraph',
    content: [
      {
        type: 'text',
        text: 'Generated by Hive Manager',
        marks: [{ type: 'em' }],
      },
    ],
  });

  return {
    version: 1,
    type: 'doc',
    content,
  };
}

/**
 * Post a feature sign-off report as a comment on a Jira epic.
 *
 * @param client - JiraClient instance
 * @param epicKey - Jira epic issue key (e.g., "PROJ-123")
 * @param data - Report data
 * @returns true if the comment was posted successfully
 */
export async function postSignOffReport(
  client: JiraClient,
  epicKey: string,
  data: SignOffReportData
): Promise<boolean> {
  try {
    const body = buildSignOffReportAdf(data);

    await client.request(`/issue/${encodeURIComponent(epicKey)}/comment`, {
      method: 'POST',
      body: JSON.stringify({ body }),
    });

    logger.info(
      `Posted sign-off report to Jira epic ${epicKey} for ${data.requirementId} (${data.passed ? 'PASSED' : 'FAILED'})`
    );
    return true;
  } catch (err) {
    logger.warn(
      `Failed to post sign-off report to Jira epic ${epicKey}: ${err instanceof Error ? err.message : String(err)}`
    );
    return false;
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function buildTableRow(label: string, value: string) {
  return {
    type: 'tableRow',
    content: [
      {
        type: 'tableCell',
        content: [
          {
            type: 'paragraph',
            content: [{ type: 'text', text: label, marks: [{ type: 'strong' }] }],
          },
        ],
      },
      {
        type: 'tableCell',
        content: [{ type: 'paragraph', content: [{ type: 'text', text: value }] }],
      },
    ],
  };
}
